[all:vars]
ansible_user=ansible 
ansible_password=ansible
ansible_become_password=ansible
owner=Steave Jobs
[frontend]
3.89.96.118

[backend]
34.204.13.222

[database] 
34.204.13.222
; [all]

; [linux]

; [windows]

; [macos]
; mac1.internal.local

; [frontend]
; frontend1.internal.local

; [backend]
; backend1.internal.local

; [database]
; db1.internal.local


; [selenium]
; win1.internal.local

; [iosbuider]
; mac1.internal.local