- name: partyspot host configurations
  hosts: all
  become: true
  roles:
    - role: landing_page
      app_name: PartySpot
      custom_html: |
        <html>
          <head><title>Test</title></head>
          <body>
            <h1>Hello from Ansible</h1>
          </body>
        </html>
      




